# Generated by Django 4.2 on 2023-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20231001_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cost',
            field=models.IntegerField(default=10),
        ),
    ]
