# Generated by Django 4.2 on 2023-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20231003_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cost',
            field=models.IntegerField(default=20),
        ),
    ]
